Vita Vas TeX Live!

   Distribucia softveru TeX Live ponuka uplny system TeX pre siroku paletu
   platforiem, ako su Unix, Macintosh, Windows a ine. Zahrna programy na 
   editaciu, sadzbu, prehliadanie a tlac TeXovskych dokumentov 
   v mnohych roznych jazykoch, ako aj obsirnu kolekciu TeXovskych makier
   a kniznic fontov.

   Distribucia obsahuje aj rozsiahlu celkovu dokumentaciu o TeXu, 
   rovnako ako sprievodnu dokumentaciu k dodanym softverovym balikom.

   Informaciu o licenciach najdete, prosim, v textovych suboroch
   [1]LICENSE.TL a [2]LICENSE.CTAN korenoveho adresara.

  Kde zacat

   Vrele Vam odporucame, aby ste si predtym, nez zacnete instalovat,
   precitali prirucku ku TeX Live. Obsahuje postupnost navodov,
   popis korenovych adresarov a dalsie veci.

   Anglicke verzie prirucky su v hierarchii [3]texmf-doc/doc/english/
   vo formatoch [4]html aj [5]pdf. Aj preklady do viacerych jazykov
   sa daju najst v [6]texmf-doc/doc/*.

   Na konci dokumentacie v oddieli "Trocha historie" najdete zoznam
   najdolezitjsich zmien v tohtorocnom vydani TeX live.

  Instalacia

   Priestorove ohranicenia formatu CD-ROM nas donutili rozdelit TeX Live
   na niekolko distribucii. Nahliadnutim do suboru 00type.TL v tomto
   korenovom adresari zistite, s ktorou mate prave do cinenia.

   live
          Uplny system na DVD; pre CD je prilis rozsiahla. Programy 
          mozete spustat priamo z DVD mechaniky; pre podrobnosti pozri 
          dokumentaciu. Druhou moznostou je nainstalovat TeX live na
          disk spustenim skriptu install-tl.sh v adresari texlive 
          pod Unixom, vratane MacOSX. V adresari setuptl najdete
          tiez Windowsovsky instalator nazvany tlpmgui.

          Live DVD obsahuje aj dalsie distribucie: proTeXt (pozri nizsie); 
          MacTeX pre MacOSX; a archiv CTAN. Kazda z tychto distribucii je
          uplne nezavisla od distribucie TeX Live, s roznymi licencnymi
          podmienkami.

   inst(allable)
          Uplny system na CD, na instalaciu pre Unix (vratane MacOSX) 
          alebo pre Windows; aby bol system v poriadku, museli sme 
          skomprimovat vsetko, co sme mohli. Preto nie je mozne spustat 
          TeX priamo z instalacneho CD; musite ho najskor nainstalovat
          na disk (odtial vyplyva jeho nazov). Vykonate to spustenim
          ./install-tl.sh pod Unixom alebo MacOSX, setuptl/tlpmgui-i386-linux
	  (Linux), alebo spustenim setuptl/tlpmgui.exe pod Windows.

   protext
          Windowsovska distribucia proTeXt je rozsirenim MiKTeXu: 
          pridava niekolko doplnkovych nastrojov a podstatne zjednodusuje 
          instalaciu. Je uplne nezavisla na instalacii TeX Live a ma
          svoje vlastne instalacne postupy. Da sa spustat nazivo (live) 
          alebo instalovat na disk. ProTeXt sa dodava na live DVD, pripadne
          (pre niektore zdruzenia pouzivatelov) na vlastnom CD.

   Prirodzene, kazde zdruzenie pouzivatelov sa podla vlastneho uvazenia rozhodne, 
   co bude distribuovat. (TUG zasiela vsetky tri vyssie uvedene disky vsetkym
   svojim clenom.)

   Podrobnosti formatu CD: CD pre Unix a Mac pouzivaju rozsirenie Rock Ridge
   standardneho formatu ISO-9660. Pre Windows sa pouzivaju rozsirenia Microsoft
   Joliet. V kazdom pripade by ste mali po namontovani vidiet uplne nazvy. 
   Ak vidite neuplne odrezane nazvy, nemozete spustat programy priamo. 
   Ak mate dobru siet a viete, ako sa napaluju disky, mozete ziskat online
   obrazy [7]ISO. Na prezeranie je dostupny aj obsah [8].

  Dokumentacia

   Vacsina dokumentacie sa da prezerat online pred instalaciou systemu TeX. 
   Na co najprijemnejsie citanie budete potrebovat prehliadac
   (ako napr. [9]Mozilla, volna verzia programu Netscape) dokumentov HTML
   a citac PDF (napr. [10]gv alebo [11]xpdf, oba su volne
   alternativy Acrobatu) pre dokumenty PDF.
     * [12]dokumentacia TeX Live (html).
     * [13]linky na vsetku dodanu PDF a HTML dokumentaciu.
     * TeX FAQ v tejto distribucii: [14]cesko/slovenske, [15]anglicke
       (pdf), [16]francuzske, [17]nemecke.

   Na  zaver niekolko pribuznych web-stranok, pre Vas prehlad. Tieto nie su
   sucastou TeX Live:
     * [18]http://tug.org/begin.html - ak ste TeXovsky zaciatocnik a/alebo 
       mate zaujem o uvodne materialy.
     * [19]http://tug.org/interest.html - vseobecny zoznam TeXovskych zdrojov
       na webe, vratane dokumentacie, systemov, balikov, fontov a dalsich veci.
     * [20]http://tug.org/ctan.html - jeden zo vstupnych bodov na
       Comprehensive TeX Archive Network (CTAN), ktory je online skladiskom
       vsetkych TeXovskych veci.
     * [21]http://tug.org/usergroups.html - celosvetovy zoznam zdruzeni 
       pouzivatelov TeXu, obsahujuci kontaktne informacie. Nevahajte a pripojte
       sa k Vami zvolenemu zdruzeniu pouzivatelov, podporite tak TeX Live 
       a ine TeXovske aktivity.

    Stastne TeXovanie! 
     _________________________________________________________________

   [22]domovska stranka TeX Live.

Odkazy

   1. LICENSE.TL
   2. LICENSE.CTAN
   3. texmf-doc/doc/english
   4. texmf-doc/doc/english/texlive-en/live.html
   5. texmf-doc/doc/english/texlive-en/live.pdf
   6. texmf-doc/doc/
   7. http://tug.org/ftp/texlive/Images/
   8. http://tug.org/ftp/texlive/Contents/
   9. http://www.mozilla.org/
  10. http://tug.org/applications/gv/
  11. http://www.foolabs.com/xpdf/
  12. texmf-doc/doc/english/texlive-en/live.html
  13. doc.html
  14. texmf-doc/doc/czechslovak/cstug/csfaq/
  15. texmf-doc/doc/english/FAQ-en/newfaq.pdf
  16. texmf-doc/doc/french/FAQ-fr/
  17. texmf-doc/doc/german/FAQ-ge/
  18. http://tug.org/begin.html
  19. http://tug.org/interest.html
  20. http://tug.org/ctan.html
  21. http://tug.org/usergroups.html
  22. http://tug.org/tex-live/
