%% iso8859-2

                  TeX Live 2008 zaprasza

TeX Live oferuje pe³ny system TeX dla wielu odmian systemu Unix, MacOSX 
i Windows (w wersji 32-bitowej). Znajduj± siê tu programy do sk³adu 
tekstów, programy do przegl±dania i drukowania dokumentów TeX-owych 
w wielu jêzykach oraz bogate kolekcje makr i fontów. 

Na p³ytce znalaz³y siê dokumentacje dotycz±ce ogólnie TeX-a, a tak¿e 
dokumentacje towarzysz±ce poszczególnym pakietom oprogramowania. 
Wiêkszo¶æ programów posiada opcjê uruchamiania --help, która mo¿e 
u³atwiæ rozpoczêcie pracy. 

Informacje licencyjne (w jêzyku angielskim) dotycz±ce redystrybucji
mo¿na znale¼æ w plikach tekstowych: [1]LICENSE.TL oraz [2]LICENSE.CTAN.
 
Jak zacz±æ

Przed rozpoczêciem instalowania warto przeczytaæ Przewodnik po TeX Live. 
Zawiera on informacje niezbêdne do korzystania z dystrybucji i prawid³owej 
instalacji systemu TeX. Wersje Przewodnika w kilku jêzykach dostêpne 
s± w formatach HTML i PDF. 

Uwaga: poni¿sze odno¶niki nie dzia³aj±, gdy instalujemy TeX Live 
z internetu. W tym wypadku nale¿y siêgn±æ do dokumentacji udostêpnionej 
w sieci: [3]http://tug.org/texlive/doc.html

Przewodnik po TeX Live (polskie t³umaczenie): 
  [4]PDF:  texmf-doc/doc/polish/texlive-pl/texlive-pl.pdf 
  [5]HTML: texmf-doc/doc/polish/texlive-pl/texlive-pl.html 

The TeX Live Guide (w jêzyku angielskim): 
  [6]PDF:  texmf-doc/doc/english/texlive-en/texlive-en.pdf 
  [7]HTML: texmf-doc/doc/english/texlive-en/texlive-en.html 

Lista najwa¿niejszych zmian znajduje siê na koñcu
dokumentacji w rozdziale [8],,Historia. Wydanie obecne''.

Instalacja

Programem instalacyjnym jest obecnie skrypt install-tl (install-tl.bat
dla Windows), który posiada dwa tryby pracy: graficzny GUI (domy¶lny
dla Windows) i tekstowy (domy¶lny dla innych systemów). Ka¿dy z tych
trybów mo¿na wymusiæ podaj±c parametr wywo³ania -gui lub -no-gui.

Po zainstalowaniu proponujemy u¿ycie tlmgr (TeX Live Manager),
który te¿ posiada analogiczne dwa tryby pracy i umo¿liwia dodawanie
b±d¼ usuwanie pakietów, ich aktualizacjê z internetu i czynno¶ci
konfiguracyjne.

Dokumentacje

Wiêkszo¶æ dokumentacji na tej p³ytce mo¿e byæ przegl±dana bez konieczno¶ci 
uprzedniego instalowania systemu TeX. Zazwyczaj s± to pliki w formatach HTML 
i/lub PDF. Do czytania dokumentów HTML potrzebna jest odpowiednia 
przegl±darka - np. Firefox lub Internet Explorer, za¶ w przypadku 
PDF - program Acrobat Reader, Ghostscript lub xpdf. 

[7]texmf-doc/english/texlive-en/texlive-en.html Oryginalna dokumentacja 
TeX Live 
[9]doc.html Katalog dostêpnych na p³ytce dokumentacji w formatach PDF i HTML 
[10]texmf-doc/doc/english/FAQ-en/newfaq.pdf  TeX Frequently Asked Questions 
                                     (odpowiedzi na czêsto zadawane pytania)

Wybrane strony, dostêpne w sieci: 
 [11]http://tug.org/begin.html Strona TeX Users Group dla pocz±tkuj±cych; 
                               zawiera odes³ania do podstawowych 
                               podrêczników; 
 [12]http://tug.org/interest.html TeX w Sieci, obszerny wybór odsy³aczy 
                               do stron WWW dotycz±cych TeX-a; 
 [13]http://tug.org/ctan.html  Dostêp do ¶wiatowych archiwów TeX-owych CTAN 
                               (Comprehensive TeX Archive Network; 
 [14]http://tug.org/usegroups.html Informacje nt. TeX Users Group i lokalnych 
                               grup u¿ytkowników systemu TeX. 

Polskie pakiety i dokumentacje

P³ytka TeX Live zawiera wiêkszo¶æ dostêpnego polskiego oprogramowania
TeX-owego i reprezentatywny wybór dokumentacji. Wirtualna Akademia TeX-owa,
prowadzona w ramach polskiej Grupy U¿ytkowników Systemu TeX GUST, 
przedstawia system TeX, a ponadto zawiera opisy wielu praktycznych makr 
i programów. Pocz±tkuj±cym polecamy szczególnie Przewodnik po systemie 
TeX (texmf-doc/doc/polish/tex-virtual-academy-pl/cototex.html).

W formacie PDF przygotowano Podrêczniki TeX-a i LaTeX-a dla pocz±tkuj±cych
(texmf-doc/doc/polish/guides-pl/index.html).

P³ytka TeX Live zawiera ponadto gotowy do u¿ycia format MeX (polski
odpowiednik formatu Plain). Format LaTeX2e jest przystosowany do obs³ugi
jêzyka polskiego po za³adowaniu pakietu "polski". Dostêpne s± oczywi¶cie 
pliki ¼ród³owe pakietów MeX i "polski"
oraz fonty przygotowane specjalnie do u¿ycia w polskojêzycznym TeX-u.

Dodatkowe programy, przydatne dla polskich u¿ytkowników, umieszczone 
zosta³y w katalogu support/polish/gustprog/ (patrz README). 
Wybór przydatnych makr dla u¿ytkowników przede wszystkim formatu 
Plain/MeX oraz makra i style do tworzenia polskich skorowidzów 
i bibliografii mo¿na znale¼æ w katalogu texmf-dist/tex/plain/gustlib 
(patrz README). 

Warto te¿ zajrzeæ na stronê polskiej Grupy U¿ytkowników Systemu TeX GUST: 
http://www.gust.org.pl 
Oprócz informacji o dzia³alno¶ci grupy, mo¿na tam znale¼æ sporo materia³ów, 
które powinny zainteresowaæ polskojêzycznych u¿ytkowników TeX-a.

Mi³ego TeX-owania! 

Strona projektu TeX Live: [15]http://tug.org/tex-live. 

Odno¶niki

   1. file:LICENSE.TL
   2. file:LICENSE.CTAN
   3. http://tug.org/texlive/doc.html
   4. file:texmf-doc/doc/polish/texlive-pl/texlive-pl.pdf
   5. file:texmf-doc/doc/polish/texlive-pl/texlive-pl.html
   6. file:texmf-doc/doc/english/texlive-en/texlive-en.pdf
   7. file:texmf-doc/doc/english/texlive-en/texlive-en.html
   8. file:texmf-doc/doc/polish/texlive-pl/texlive-pl.html
   9. file:doc.html
  10. file:texmf-doc/doc/english/FAQ-en/newfaq.pdf
  11. http://tug.org/begin.html
  12. http://tug.org/interest.html
  13. http://tug.org/ctan.html
  14. http://tug.org/usergroups.html
  15. http://tug.org/texlive/

--------------------------------
17 sierpnia 2008

